# Generated by Django 4.0.6 on 2022-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, unique=True)),
                ('cidade', models.CharField(max_length=128)),
                ('bairro', models.CharField(max_length=128)),
                ('logradouro', models.CharField(max_length=256)),
                ('complemento', models.CharField(max_length=256)),
            ],
        ),
    ]
